/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { PaymentPlanV1, PaymentPlanV1Interface } from "../PaymentPlanV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "wNFTContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wNFTTokenId",
        type: "uint256",
      },
    ],
    name: "getNextPayment",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "wNFTContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "wNFTTokenId",
        type: "uint256",
      },
    ],
    name: "pay",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class PaymentPlanV1__factory {
  static readonly abi = _abi;
  static createInterface(): PaymentPlanV1Interface {
    return new utils.Interface(_abi) as PaymentPlanV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PaymentPlanV1 {
    return new Contract(address, _abi, signerOrProvider) as PaymentPlanV1;
  }
}
